resources:
  - namespace.yaml
  - chart.yaml
  - podmonitor.yaml
  - dashboard.yaml
  - httproute.yaml
  - epp-rbac.yaml
  - epp.yaml
  - inferencepool.yaml
  - referencegrant.yaml
  - aigatewayroute.yaml
