apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - project.yaml
  - warehouse.yaml
  - stages.yaml
  - project-config.yaml
  - vault-secret.yaml
  - analysistemplate.yaml
