apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: froystein-jp
  namespace: froystein-jp
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
    - stageSelector:
        name: prod
      autoPromotionEnabled: false
