apiVersion: v1
kind: Service
metadata:
  name: ocp-upgrade-lab
  namespace: ocp-upgrade-lab
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.1.50
spec:
  type: LoadBalancer
  selector:
    kubevirt.io/vm: ocp-upgrade-lab
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
    - name: api
      port: 6443
      targetPort: 6443
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
