apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - inference-pool-crds.yaml
  - envoy-gateway.yaml
  - ai-gateway-crds.yaml
  - ai-gateway.yaml
  - gateway.yaml
