apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - chart.yaml
  - vso-chart.yaml
  - httproute.yaml
  - backup-cronjob.yaml
  - backup-rbac.yaml
  - vault-auth.yaml
