apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: ghcr.io/prometheus-community/charts
    targetRevision: 79.4.1
    helm:
      releaseName: kube-prometheus
  destination:
    namespace: kube-prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
