apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-z1
  namespace: argocd
spec:
  project: default
  source:
    chart: gateway-helm
    repoURL: docker.io/envoyproxy
    targetRevision: v1.5.4
    helm:
      parameters:
        - name: certgen.job.securityContext.runAsGroup
          value: "1001580000"
  destination:
    namespace: kube-prometheus
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
