resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.0/manifests/install.yaml
  - namespace.yaml

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-server-deployment-patch.yaml
    target:
      kind: Deployment
      name: argocd-server

namespace: argocd
