resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v3.2.0/manifests/install.yaml
  - namespace.yaml

patches:
  - path: argocd-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-rbac-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-rbac-cm
  - path: argocd-cmd-params-cm-patch.yaml
    target:
      kind: ConfigMap
      name: argocd-cmd-params-cm

namespace: argocd
